# start_time: "2008-01-01"
# end_time: "2023-12-31"
# fit_start_time: "2008-01-01"
# fit_end_time: "2019-12-31"
# instruments: "csi300"
# infer_processors:
#   - class: RobustZScoreNorm
#     kwargs:
#       fields_group: feature
#       clip_outlier: true
#   - class: Fillna
#     kwargs:
#       fields_group: feature
# learn_processors:
#   - class: DropnaLabel
#   - class: CSRankNorm
#     kwargs:
#       fields_group: label
# label:
#   - "Ref($close, -2)/Ref($close, -1) - 1"